name: Test

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Train:
    uses: ./.github/workflows/train.yml
    secrets: inherit
  pull-and-run:
    name: pull-and-run
    needs: [Train]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker code
        uses: actions/checkout@v4

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: shivsantoshiisc
          password: ${{ secrets.DOCKERPW }}

      - name: Pull latest mlops docker image
        run: docker pull shivsantoshiisc/mlops:latest

      - name: Run Docker image to check score
        id: run_image
        run: |
          MODEL_SCORE=$(docker run shivsantoshiisc/mlops:latest | tail -n 1)
          echo "model score = $MODEL_SCORE"
          if (( $(echo "$MODEL_SCORE > 0.50" | bc -l) )); then
            echo "passing - MODEL_SCORE > 0.5"
          else
            echo "failing - MODEL_SCORE < 0.5."
            exit 1
          fi
