name: Train

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shivsantoshiisc
          password: ${{ secrets.DOCKERPW }}

      - name: Build and push Docker image
        run: |
          docker build -t shivsantoshiisc/test_1st:latest .
          docker push shivsantoshiisc/test_1st:latest
